from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol


@dataclass(frozen=True)
class ScreenshotOptions:
    path: str
    full_page: bool = False


@dataclass(frozen=True)
class AgentPage:
    page_id: int
    url: str | None = None
    title: str | None = None
    backend: str = "axi"


class BrowserBackend(Protocol):
    name: str

    def open(self, url: str) -> str: ...

    def new(self) -> str: ...

    def snapshot(self) -> str: ...

    def text(self) -> str: ...

    def click(self, target: str) -> str: ...

    def fill(self, target: str, text: str) -> str: ...

    def type_text(self, text: str) -> str: ...

    def press(self, key: str) -> str: ...

    def scroll(self, direction: str) -> str: ...

    def wait(self, target: str) -> str: ...

    def back(self) -> str: ...

    def screenshot(self, options: ScreenshotOptions) -> str: ...

    def evaluate(self, code: str) -> str: ...


    def print_page_id(self, *, force_new: bool = False) -> None: ...

    def print_state(self, *, thread: str) -> None: ...

    def print_list(self) -> None: ...

    def close(self) -> int: ...

    def focus(self) -> int: ...

    def close_matching(self, pattern: str) -> int: ...

    def bridge_stop(self) -> int: ...

    def capture_snapshot(self) -> Any: ...
